### ISSUE TITLE
Podspec includes incorrect search path

### ISSUE THREAD

**Issue by abbeycode** [PaddleHQ/Paddle-MAS#1]
The Podspec line

    s.xcconfig            = { 'FRAMEWORK_SEARCH_PATHS' => '"${PODS_ROOT}/Paddle"' }

should read

    s.xcconfig            = { 'FRAMEWORK_SEARCH_PATHS' => '"${PODS_ROOT}/Paddle-MAS"' }

**Comment by avalore** [comment]
Good spot! This has now been fixed.

**Comment by abbeycode** [comment]
That's strange... now my `xcconfig` contains this line:

    FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Paddle" "$(PODS_ROOT)/Paddle-MAS"

It looks like you can remove the xcconfig line altogether. Having a `vendored_framework` seems to automatically add it to the search path. When I remove it locally, I end up with this:

    FRAMEWORK_SEARCH_PATHS = $(inherited) "$(PODS_ROOT)/Paddle-MAS"
