### ISSUE TITLE
Resources have executable permissions

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Paddle-MAS#10]
Checking out one of our apps that uses PaddleMAS.framework using RB App Checker Lite shows that all the resources in the framework have executable permissions when they should not.

It shows "**25 data files have executable permissions, but should not.**"

<img width="1028" alt="screen shot 2016-11-24 at 11 14 22 am" src="https://cloud.githubusercontent.com/assets/2223932/20605108/a016fee6-b237-11e6-805d-cc98189ebb09.png">

**Comment by avalore** [comment]
Thanks @tunabelly we'll look into this.

**Comment by avalore** [comment]
Took a little while to get to the bottom of this one. The repo/SDK has the correct permissions set but depending on how you get a copy of the SDK the permissions may be incorrect (https://github.com/isaacs/github/issues/552)

If you download the `.zip` and extract automatically through OS X then the executable bit will be set, even though it wasn't originally. The easiest way is to clone the repo instead, which should keep the permissions.

**Comment by tunabelly** [comment]
Ok, thanks for figuring this out. I'll make sure to clone the repo from now on.
