### ISSUE TITLE
semaphore_wait_trap when returning from background

### ISSUE THREAD

**Issue by floschliep** [PaddleHQ/Paddle-MAS#8]
After upgrading to v1.1.6, I repeatedly experienced that my app froze after returning from another app (presumably on applicationDidBecomeActive:). This seems to be caused by the Paddle framework:

![bildschirmfoto 2016-05-19 um 17 24 59](https://cloud.githubusercontent.com/assets/1427112/15400367/9023301c-1deb-11e6-91af-a08fdf880749.png)

After replacing the framework with v1.1.5 everything was back to normal.

**Comment by avalore** [comment]
So far we've been unable to recreate this issue in the recent update v1.1.7. If this persists could you please email a sample build with the issue.
